name = "MatheKapierenMitJulia"
uuid = "779c5319-98a4-4a64-b5c3-f3a76430d20b"
authors = ["Oliver Krischer"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
