project:
  type: website

engines: ['julia']

website:
  title: "Mathe Kapieren mit Julia"
  sidebar:
    style: docked
    search: true
    contents: auto

format:
  html:
    theme: cosmo
    toc: true
    code-tools: true
    code-annotations: below
