project:
  type: website

engines: ['julia']

lang: de

website:
  title: "Mathe Kapieren mit Julia"
  sidebar:
    style: docked
    search: true
    contents: auto

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    respect-user-color-scheme: true
    highlight-style: github
    toc: true
    code-overflow: wrap
    code-tools: true
    code-annotations: below
